Adapt data structure of conventional pp to scalar data template
rl-institut/oemof-B3 pull request #51
Opened 2021-07-15 10:10 UTC by juliusmeier

The prepared data of conventional power plant data is adapted to the template of scalar data.
Closes issue #48

2021-07-15 10:29 UTC, jnnr requested changes
Thanks for your work! I produced the resource and found the following:

* name, type should be None
* unit should be None for chp and efficiency
* map carrier and tech from OPSD terminology to oemoflex's carriers and techs
* reference: add the items to a bibtex (references_input_data.bib, separate from the bibtex that is already included in the docs) and state the citation key here.

2021-07-15 14:30 UTC, juliusmeier commented
- [ ] map carrier and tech from OPSD terminology to oemoflex's carriers and techs

2021-07-22 11:26 UTC, juliusmeier reviewed
Done

2021-07-22 11:26 UTC, juliusmeier reviewed
Done

2021-07-22 13:47 UTC, jnnr commented on scripts/prepare_conv_pp.py
>      b3_regions_content = yaml.load(b3_regions_yaml, Loader=yaml.FullLoader)
```suggestion
    with open(in_path3, "r", encoding="utf-8") as b3_regions_yaml:
        b3_regions_content = yaml.load(b3_regions_yaml, Loader=yaml.FullLoader)
```

2021-07-22 13:54 UTC, merged