First basic scenarios
rl-institut/oemof-B3 pull request #91
Opened 2021-11-22 16:17 UTC by jnnr

2022-01-25 10:32 UTC, SabineHaas commented
@jnnr there's a failing test and a merge conflict. Would you like to solve this, before my review? 

The merge conflict might come from #107  let me know if you need help.

2022-01-25 17:11 UTC, jnnr commented
@SabineHaas: I added a new scenario in 4ff0904 to test how the current scenario building process works. My impression: It works, but may become a bit hard to read with many scenario changes.

2022-01-26 12:17 UTC, SabineHaas reviewed
Thank you @jnnr for preparing these scenarios :) . I already have some comments and questions, but haven't finished to go through the whole PR, yet.

- You could add vehicle time series already (however, Brandenburg2019 is still a dummy).
- Some rules like `prepare_feedin` have to be run separately to get the `_resources`. This does not necessarily have to be fixed in this PR.
- How do I get `ts_load_heat.csv` as resource?  --> Maybe you can provide your `_resources` to me  - I guess that would be easiest.

FYI I needed to adapt `scalars_base_PR#91.csv` to be able to prepare the scalars with the current code: 
- replace comma with dot in one `var_value`
- use comma as separator
- remove columns source and comment (due to commas)

2022-02-22 11:06 UTC, SabineHaas requested changes
Nice! Thank you @jnnr preparing these scenarios and also improving the code in this PR!

I've noticed that the rules that prepare resources (e.g. demands) are run automatically now when running `snakemake -j1 results/base-2050/postprocessed` :+1: (:

I was missing ts_load_h2 and just used the same file as ts_load_ch4 as they are both konstant. I have added it to /raw.

After the issue with the datetimeindex is fixed, I can test the full run.

2022-02-22 11:06 UTC, SabineHaas commented on scenarios/base-2050.yml
> +
Seems like this file is missing 'datetimeindex'. 

```
Traceback (most recent call last):
  File "scripts/build_datapackage.py", line 238, in <module>
    start=scenario_specs["datetimeindex"]["start"],
KeyError: 'datetimeindex'
```

scenario_specs is the loaded data of `scenarios/base-2050.yml`

2022-02-22 11:16 UTC, jnnr commented on oemof_b3/model/foreign_keys_update.yml
> +    'electricity-transmission',
Yes, exactly.

2022-02-23 09:13 UTC, SabineHaas commented
@jnnr thanks for adding the datetimeindex to the scenarios, I have tested a full run now. 

I noticed that the results are quite unrealistic, as each demand is covered by only import/shortage. This is due to low costs for import and shortage. 
You could set high shortage costs to receive more realistic results. 
You could also add emission_factors as in `base-scenario.csv` given.  But I also understand if you don't want to make it more complicated. However, I think it would be convenient as this would show that all current functionalities/data works with the current code.

2022-02-23 09:52 UTC, jnnr commented on oemof_b3/tools/data_processing.py
> +    )
You are right. It should only appear if how == 'left', not if how == 'outer'. Will do that

2022-02-23 09:52 UTC, jnnr commented on oemof_b3/tools/data_processing.py
> +    # Where df_a contains no new data, use df_b
Yes.

2022-02-23 10:05 UTC, jnnr commented on scripts/create_empty_scalars.py
> +    empty_scalars.to_csv(destination, sep=";")
You are right!

2022-02-23 16:13 UTC, SabineHaas approved these changes
Thanks for adding bev time series :) 
I have adapted the scalars and uploaded them to /raw: added emission_factors, emission_limit and adapted shortage costs to a very high value and exports costs to a low negative value.

I tested the scenario base-2050 but not the other scenarios.

2022-02-25 11:16 UTC, jnnr commented
I tested base-2050 and base-2050-high_capacity_cost

2022-02-25 11:17 UTC, merged